### ISSUE TITLE
The line login = input(str("Please enter the password for " + l_n + " Username: ")) does not work in the boot sequance.

### ISSUE THREAD

**Issue by MicklePickl** [LucaBarbaLata/Rudolf-OS#1]

**Comment by LucaBarbaLata** [comment]
hello. i am now seeing this issue. i am working on a fix rn. sorry for any inconvenience created

**Comment by LucaBarbaLata** [comment]
The issue is now fixed. Please create a folder with the name "user" alongside with the other files for the program to work
